if MMO==nil then
	MMO={};
end



MMO.ACCOUNT_STATUS=
{
	ACCOUNT_STATUS_MANAGER_STATUS_MASK = 0xF,
	ACCOUNT_STATUS_NORMAL_STATUS_MASK = 0xFF0,
	ACCOUNT_STATUS_ANTI_ADDICTION_STATUS_MASK = 0xF000,
	ACCOUNT_STATUS_MANAGER_STATUS_BLOCK = 0x1,
	ACCOUNT_STATUS_NORMAL_STATUS_ADULT = 0x10,
	ACCOUNT_STATUS_ANTI_ADDICTION_STATUS_LEVEL0 = 0,
	ACCOUNT_STATUS_ANTI_ADDICTION_STATUS_LEVEL1 = 0x1000,
	ACCOUNT_STATUS_ANTI_ADDICTION_STATUS_LEVEL2 = 0x2000,
	ACCOUNT_STATUS_BAT_LOGIN = 0x10000,

};




MMO.ACCOUNT_TYPE=
{
	ACCOUNT_TYPE_ALL = 0,
	ACCOUNT_TYPE_TEMP = 1,
	ACCOUNT_TYPE_DELETED = 2,
	ACCOUNT_TYPE_NORMAL = 100,
	ACCOUNT_TYPE_UC = 103,
	ACCOUNT_TYPE_MI = 104,
	ACCOUNT_TYPE_BAIDU = 105,
	ACCOUNT_TYPE_HUAWEI = 112,
	ACCOUNT_TYPE_360 = 117,

};




MMO.CLIENT_TYPE=
{
	CLIENT_TYPE_PC_FOR_OTHER = 0,
	CLIENT_TYPE_IOS_FOR_OTHER = 1,
	CLIENT_TYPE_IOS_FOR_UC = 2,
	CLIENT_TYPE_ANDROID_FOR_OTHER = 16,
	CLIENT_TYPE_ANDROID_FOR_UC = 17,
	CLIENT_TYPE_ANDROID_FOR_MI = 18,
	CLIENT_TYPE_ANDROID_FOR_BAIDU = 19,
	CLIENT_TYPE_ANDROID_FOR_HUAWEI = 20,
	CLIENT_TYPE_ANDROID_FOR_360 = 21,

};





