if MMO==nil then
	MMO={};
end



MMO.CLIENT_NETWORK_TYPE=
{
	CLIENT_NETWORK_TYPE_UNKNOW = 0,
	CLIENT_NETWORK_TYPE_CARRIER_DATA_NETWORK = 1,
	CLIENT_NETWORK_TYPE_LOCAL_AREA_NETWORK = 2,

};




MMO.GLOBAL_SST_ID=
{
	GLOBAL_SST_ID_PARAM1 = 1,
	GLOBAL_SST_ID_PARAM2 = 2,
	GLOBAL_SST_ID_PARAM3 = 3,
	GLOBAL_SST_ID_PARAM4 = 4,
	GLOBAL_SST_ID_PARAM5 = 5,

};




MMO.LANGUAGE_TYPE=
{
	LANGUAGE_TYPE_EN = 0,--英文
	LANGUAGE_TYPE_SCN = 1,--简体中文
	LANGUAGE_TYPE_TCN = 2,--繁体中文
	LANGUAGE_TYPE_JP = 3,--日文
	LANGUAGE_TYPE_KR = 4,--韩文
	LANGUAGE_TYPE_FR = 5,--法文
	LANGUAGE_TYPE_DE = 6,--德文
	LANGUAGE_TYPE_ES = 7,--西班牙文
	LANGUAGE_TYPE_IT = 8,--意大利文
	LANGUAGE_TYPE_VN = 9,--越南文
	LANGUAGE_TYPE_TH = 10,--泰文
	LANGUAGE_TYPE_MAX = 11,

};




MMO.MASK_WORD_TYPE=
{
	MASK_WORD_TYPE_PLAYER_NAME = 1,
	MASK_WORD_TYPE_GUILD_NAME = 1<<1,
	MASK_WORD_TYPE_CHAT_CONTENT = 1<<2,

};




MMO.OBJECT_ID_TYPE=
{
	OBJECT_ID_ACCOUNT_ID = 0,
	OBJECT_ID_ITEM_ID = 1,
	OBJECT_ID_GUILD_ID = 2,
	OBJECT_ID_MAIL_ID = 3,
	OBJECT_ID_ROLE_ID = 4,
	OBJECT_ID_PET_ID = 5,
	OBJECT_ID_NPC_ID = 6,
	OBJECT_ID_ITEMDROP_ID = 7,
	OBJECT_ID_SKILL_EVENT = 8,

};




MMO.OBJECT_TYPES=
{
	OBJECT_TYPE_LOGIN_ENTRANCE = 0x61,
	OBJECT_TYPE_LOGIN_ENTRANCE_GROUP = 0x62,
	OBJECT_TYPE_PLAYER_QUEUER = 0x63,
	OBJECT_TYPE_ACCOUNT_AUTH_ADAPTER = 0x64,
	OBJECT_TYPE_ACCOUNT_AUTH_ADAPTER_GROUP = 0x65,
	OBJECT_TYPE_PLAYER = 0x66,
	OBJECT_TYPE_CONFIG_DATA_ADAPTER = 0x67,
	OBJECT_TYPE_GM_COMMAND_CENTER = 0x68,
	OBJECT_TYPE_HTTP_REQUESTER = 0x69,
	OBJECT_TYPE_HTTP_SERVICE = 0x6A,
	OBJECT_TYPE_LOG_ADAPTER = 0x6B,
	OBJECT_TYPE_RESERVE1 = 0x6C,
	OBJECT_TYPE_RESERVE2 = 0x6D,
	OBJECT_TYPE_RESERVE3 = 0x6E,
	OBJECT_TYPE_PLAYER_DB_ADAPTER = 0x6F,
	OBJECT_TYPE_PLAYER_DB_ADAPTER_GROUP = 0x70,
	OBJECT_TYPE_PAY_AGENT = 0x71,
	OBJECT_TYPE_CHAT_CENTER = 0x72,
	OBJECT_TYPE_MAIL_SYSTEM = 0x73,
	OBJECT_TYPE_RANK_GROUP = 0x74,
	OBJECT_TYPE_RANK_SYSTEM = 0x75,
	OBJECT_TYPE_GLOBAL_RANK_SYSTEM = 0x76,
	OBJECT_TYPE_GAME_SCENE_MANAGER = 0x77,
	OBJECT_TYPE_GAME_SCENE_GROUP = 0x78,
	OBJECT_TYPE_GAME_SCENE = 0x79,

};




MMO.REGION_TYPE=
{
	REGION_TYPE_OTHER = 0,
	REGION_TYPE_GLOBAL = 1,
	REGION_TYPE_MAX = 2,

};




MMO.SERVER_STATUS=
{
	SERVER_STATUS_OFFLINE = 0,
	SERVER_STATUS_MAINTAIN = 1,
	SERVER_STATUS_IDLE = 2,
	SERVER_STATUS_SMOOTH = 3,
	SERVER_STATUS_BUSY = 4,
	SERVER_STATUS_FULL = 5,

};




MMO.SYSTEM_SHUTDOWN_LEVEL=
{
	SYSTEM_SHUTDOWN_LEVEL_ALONE = 0,
	SYSTEM_SHUTDOWN_LEVEL1 = 1,
	SYSTEM_SHUTDOWN_LEVEL2 = 2,

};




MMO.SYSTEM_SHUTDOWN_TYPE=
{
	SYSTEM_SHUTDOWN_TYPE_CORE = 1,
	SYSTEM_SHUTDOWN_TYPE_ACCOUNT_AUTH_ADAPTER = (1<<1),
	SYSTEM_SHUTDOWN_TYPE_CONFIG_DATA_ADAPTER = (1<<2),
	SYSTEM_SHUTDOWN_TYPE_GM_COMMAND_CENTER = (1<<3),
	SYSTEM_SHUTDOWN_TYPE_HTTP_REQUESTER = (1<<4),
	SYSTEM_SHUTDOWN_TYPE_HTTP_SERVICE = (1<<5),
	SYSTEM_SHUTDOWN_TYPE_LOG_ADAPTER = (1<<6),
	SYSTEM_SHUTDOWN_TYPE_PAY_AGENT = (1<<7),
	SYSTEM_SHUTDOWN_TYPE_PLAYER_DB_ADAPTER = (1<<8),
	SYSTEM_SHUTDOWN_TYPE_BATTLE_SYSTEM = (1<<9),
	SYSTEM_SHUTDOWN_TYPE_CHAT_CENTER = (1<<10),
	SYSTEM_SHUTDOWN_TYPE_MAIL_SYSTEM = (1<<11),
	SYSTEM_SHUTDOWN_TYPE_RANK_SYSTEM = (1<<12),
	SYSTEM_SHUTDOWN_TYPE_GLOBAL_RANK_SYSTEM = (1<<13),
	SYSTEM_SHUTDOWN_TYPE_ALL = 0x7FFFFFFF,

};





