if MMO==nil then
	MMO={};
end

--默认AI选项

MMO.ACTION_DEFAULT_TP=
{
	ADT_NONE = 0,--无
	ADT_IDLE = 1,--待机
	ADT_ATTACK = 2,--攻击
	ADT_STRIKE_BACK = 3,--反击
	ADT_MAX = 4,

};


--Actions例表任务执行方式

MMO.ACTION_EXEC_TYPE=
{
	RANDOM = 1,--随机选一执行
	PARALLEL = 2,--遍历执行

};


--AI行为分类

MMO.ACTION_TYPE=
{
	NONE = 0,--不使用
	ROOT = 1,--根节点
	BASE = 2,--基本处理
	TIMES = 3,--次数
	INTERVAL = 4,--间隔
	ACTION_MOVE_POS = 5,--移动
	PCONDITION = 6,--条件判断
	CAST_SKILL = 7,--放技能
	MOVE_TARGET = 8,--移动到目标
	ACTION_RANDOM_POS = 9,--随机移动

};


--比较操作

MMO.AICONDITION_OP=
{
	EQ = 1,--相等
	NEQ = 2,--不相等
	GT = 3,--大于
	GTE = 4,--大于等于
	LT = 5,--小于
	LTE = 6,--小于等于

};


--条件类型

MMO.AICONDITION_TYPE=
{
	P_CHAR_ATTR = 1,--角色属性
	P_MOVE_POS = 2,--移动坐标
	P_MOVE_STOP = 3,--停止坐标
	P_CAST_SKILL = 4,--放技能
	P_INTERVAL = 5,--间隔
	P_TIMES = 6,--次数
	P_DIE = 7,--死亡
	P_DIE_TARGET = 8,--目标死亡

};


--AI操作

MMO.AI_ACTION=
{
	AI_ACTION_USE_SKILL = 0,
	AI_ACTION_USE_ITEM = 1,
	AI_ACTION_DO_NOTHING = 2,
	AI_ACTION_SKIP = 3,
	AI_ACTION_MAX = 4,

};


--AI标志位

MMO.AI_FLAG=
{
	AI_FLAG_IS_MULTI_TARGET = 1,--多目标
	AI_FLAG_IS_ELEMENT_WATER = 1<<1,--水属性
	AI_FLAG_IS_ELEMENT_FIRE = 1<<2,--火属性
	AI_FLAG_IS_ELEMENT_WIND = 1<<3,--风属性
	AI_FLAG_IS_ELEMENT_EARTH = 1<<4,--地属性
	AI_FLAG_IS_ELEMENT_LIGHT = 1<<5,--光属性
	AI_FLAG_IS_ELEMENT_DARK = 1<<6,--暗属性
	AI_FLAG_SELECT_MIN_ELEMENT_RES = 1<<7,--选择最低属性
	AI_FLAG_SKIP_ON_HAVE_ELEMENT_RES = 1<<8,--同属性跳过

};


--目标选择分类

MMO.AI_PICK_TARGET_TYPE=
{
	PICK_ATTACK = 1,--攻击目标
	PICK_STRIKE_BACK = 2,--反击目标
	AI_PICK_TYPE_MAX = 3,

};


--AI触发器类型

MMO.AI_TRIGGER_TYPE=
{
	AI_TRIGGER_TYPE_ON_RANDOM = 1001,--随机触发
	AI_TRIGGER_TYPE_ON_SELF_HP_RANGE = 1002,--自身HP范围触发
	AI_TRIGGER_TYPE_ON_SELF_MP_RANGE = 1003,--自身MP范围触发
	AI_TRIGGER_TYPE_ON_FRIEND_HP_RANGE = 1004,--友方HP范围触发
	AI_TRIGGER_TYPE_ON_FRIEND_MP_RANGE = 1005,--友方MP范围触发
	AI_TRIGGER_TYPE_ON_FRIEND_MULTI_HP_RANGE = 1006,--友方们HP范围触发
	AI_TRIGGER_TYPE_ON_FRIEND_MULTI_MP_RANGE = 1007,--友方们MP范围触发
	AI_TRIGGER_TYPE_ON_ENEMY_HP_RANGE = 1008,--敌方HP范围触发
	AI_TRIGGER_TYPE_ON_ENEMY_MP_RANGE = 1009,--敌方MP范围触发
	AI_TRIGGER_TYPE_ON_ENEMY_MULTI_HP_RANGE = 1010,--敌方们HP范围触发
	AI_TRIGGER_TYPE_ON_ENEMY_MULTI_MP_RANGE = 1011,--敌方们MP范围触发
	AI_TRIGGER_TYPE_ON_SELF_HAVE_BUFF = 1012,
	AI_TRIGGER_TYPE_ON_SELF_NOT_HAVE_BUFF = 1013,
	AI_TRIGGER_TYPE_ON_FRIEND_HAVE_BUFF = 1014,
	AI_TRIGGER_TYPE_ON_FRIEND_NOT_HAVE_BUFF = 1015,
	AI_TRIGGER_TYPE_ON_FRIEND_HAVE_GAIN_BUFF = 2025,
	AI_TRIGGER_TYPE_ON_FIREND_HAVE_DEBUFF_BUFF = 2026,
	AI_TRIGGER_TYPE_ON_ENEMY_HAVE_BUFF = 1016,
	AI_TRIGGER_TYPE_ON_ENEMY_NOT_HAVE_BUFF = 1017,
	AI_TRIGGER_TYPE_ON_ENEMY_HAVE_GAIN_BUFF = 2023,
	AI_TRIGGER_TYPE_ON_ENEMY_HAVE_DEBUFF_BUFF = 2024,
	AI_TRIGGER_TYPE_ON_TIME = 1018,
	AI_TRIGGER_TYPE_ON_SELF_HAVE_STATUS = 1020,
	AI_TRIGGER_TYPE_ON_FRIEND_HAVE_STATUS = 1021,
	AI_TRIGGER_TYPE_ON_ENEMY_HAVE_STATUS = 1022,
	AI_TRIGGER_TYPE_ON_ENEMY_DEF_LESS_THAN_MDF = 2001,
	AI_TRIGGER_TYPE_ON_ENEMY_MDF_LESS_THAN_DEF = 2002,
	AI_TRIGGER_TYPE_ON_ENEMY_WATER_RES_RANGE = 2010,
	AI_TRIGGER_TYPE_ON_ENEMY_FIRE_RES_RANGE = 2011,
	AI_TRIGGER_TYPE_ON_ENEMY_WIND_RES_RANGE = 2012,
	AI_TRIGGER_TYPE_ON_ENEMY_EARTH_RES_RANGE = 2013,
	AI_TRIGGER_TYPE_ON_ENEMY_LIGHT_RES_RANGE = 2014,
	AI_TRIGGER_TYPE_ON_ENEMY_DARK_RES_RANGE = 2015,

};


--属性配置标志位

MMO.CHAR_ATTR_CONFIG_FLAG=
{
	CHAR_ATTR_CONFIG_FLAG_IS_RES = (1 << 0),

};


--角色势力

MMO.CHAR_FORCE_TYPE=
{
	CHAR_FORCE_TYPE_PLAYER = 0,
	CHAR_FORCE_TYPE_PET = 1,
	CHAR_FORCE_TYPE_NPC = 2,
	CHAR_FORCE_TYPE_MONSTER = 3,
	CHAR_FORCE_TYPE_MAX = 4,

};


--角色等级配置标志位

MMO.CHAR_LEVEL_CONFIG_FLAG=
{
	CHAR_LEVEL_CONFIG_FLAG_NONE = (1 << 0),--无

};


--移动类型标识

MMO.CHAR_MOVE_TYPE=
{
	CHAR_MOVE_TYPE_WALK = 0,--走
	CHAR_MOVE_TYPE_RUN = 1,--跑
	CHAR_MOVE_TYPE_RIDE = 2,--乘骑
	CHAR_MOVE_TYPE_MAX = 3,

};


--角色关系

MMO.CHAR_RELATION=
{
	CHAR_RELATION_SELF = 1,--自身
	CHAR_RELATION_ENEMY = (1<<1),--敌对
	CHAR_RELATION_FRIEND = (1<<2),--友好
	CHAR_RELATION_TEAM_MEMBER = (1<<3),--队友

};


--朝向

MMO.FACE_DIR_TYPE=
{
	FACE_DIR_UP = 0,--朝上
	FACE_DIR_UP_RIGHT = 1,--朝右上
	FACE_DIR_RIGHT = 2,--朝右
	FACE_DIR_DOWN_RIGHT = 3,--朝右下
	FACE_DIR_DOWN = 4,--朝下
	FACE_DIR_DOWN_LEFT = 5,--朝左下
	FACE_DIR_LEFT = 6,--朝左
	FACE_DIR_UP_LEFT = 7,--朝左上

};


--性别

MMO.GENDER_TYPE=
{
	GENDER_TYPE_FEMALE = 0,--女
	GENDER_TYPE_MAIL = 1,--男
	GENDER_TYPE_MAX = 2,

};


--地图对象状态

MMO.MAP_OBJECT_STATUS=
{
	MOBJ_STATUS_DEATH = (1 << 0),--死亡状态
	MOBJ_STATUS_INVI = (1 << 1),--无敌状态
	MOBJ_STATUS_BATTLING = (1 << 2),--战斗状态
	MOBJ_STATUS_FROST = (1 << 3),--冻结状态
	MOBJ_STATUS_CONFUSION = (1 << 4),--混乱状态
	MOBJ_STATUS_MOVING = (1 << 5),--行走状态
	MOBJ_STATUS_RUN = (1 << 6),--奔跑状态
	MOBJ_STATUS_RIDE = (1 << 7),--骑乘状态
	MOBJ_STATUS_CAN_NOT_MOVE = (1 << 10),--不能移动
	MOBJ_STATUS_CAN_NOT_NORMAL_ATTACK = (1 << 11),--不能普通攻击
	MOBJ_STATUS_CAN_NOT_USE_MAG_SKILL = (1 << 12),--不能使用魔法
	MOBJ_STATUS_CAN_NOT_USE_PHY_SKILL = (1 << 13),--不能使用技能
	MOBJ_STATUS_CAN_NOT_USE_ITEM = (1 << 14),--不能使用道具
	MOBJ_STATUS_NOT_BE_HP_DEC = (1 << 15),--不能被伤害
	MOBJ_STATUS_NOT_BE_MP_DEC = (1 << 16),--不能被减蓝
	MOBJ_STATUS_NOT_BE_CAST_DEBUFF = (1 << 17),--不能被施放减益效果

};


--NPC配置标志位

MMO.NPC_CONFIG_FLAG=
{
	NPC_CONFIG_FLAG_AUTO_TRIGGER = 1,--自动触发
	NPC_CONFIG_FLAG_IS_BOSS = 1<<1,--是Boss

};


--NPC功能例表

MMO.NPC_FUN_TYPE=
{
	MAP_LINK = 1,--地图传送

};


--职业

MMO.PROFESSION_TYPE=
{
	PROFESSION_TYPE_NONE = 0,--无职业
	PROFESSION_TYPE_WARRIOR = 1,--战士
	PROFESSION_TYPE_WIZARD = 2,--法师
	PROFESSION_TYPE_PRIEST = 3,--祭司
	PROFESSION_TYPE_MAX = 4,

};


--种族类型

MMO.RACE_TYPE=
{
	RACE_TYPE_OTHER = 0,--其他
	RACE_TYPE_HUMAN = 1,--人形
	RACE_TYPE_ELEMENT = 2,--元素
	RACE_TYPE_SPRITE = 3,--精灵
	RACE_TYPE_ANIMAL = 4,--动物
	RACE_TYPE_PLANT = 5,--植物
	RACE_TYPE_INSECT = 6,--昆虫
	RACE_TYPE_ANGEL = 7,--天使
	RACE_TYPE_DEVIL = 8,--恶魔
	RACE_TYPE_DRAGONS = 9,--龙类
	RACE_TYPE_SOULS = 10,--亡灵
	RACE_TYPE_INVISIBLE = 11,--无形
	RACE_TYPE_SACRED = 12,--圣兽
	RACE_TYPE_MECHANICAL = 13,--机械
	RACE_TYPE_MAX = 14,

};


--系统预留角色属性ID

MMO.RESERVE_CHAR_ATTR_TYPE=
{
	RESERVE_CHAR_ATTR_NONE = 0,--无
	RESERVE_CHAR_ATTR_WALK_SPEED = 1,--走动速度
	RESERVE_CHAR_ATTR_RUN_SPEED = 2,--跑动速度
	RESERVE_CHAR_ATTR_RIDE_SPEED = 3,--乘骑速度
	RESERVE_CHAR_ATTR_MAX = 100,--最大预留属性ID

};





