if MMO==nil then
	MMO={};
end



MMO.CONFIG_DATA_LOAD_FLAG=
{
	CDLF_MASK_WORD_LIST = 1,
	CDLF_STORAGE_STRING_TABLE = (1<<1),
	CDLF_ITEM_DROP_BAG_LIST = (1<<2),
	CDLF_SCRIPT_LIST = (1<<3),
	CDLF_ITEM_CONFIG = (1<<4),
	CDLF_GAME_SCATTERED_CONFIG = (1<<5),
	CDLF_SHOP_CONFIG = (1<<6),
	CDLF_QUEST_CONFIG = (1<<7),
	CDLF_RANK_CONFIG = (1<<8),
	CDLF_CHAR_CONFIG = (1<<9),
	CDLF_SCENE_CONFIG = (1<<10),
	CDLF_SKILL_CONFIG = (1<<11),
	CDLF_MAP_BLOCKS = (1<<12),

};




MMO.CONFIG_DATA_TYPE=
{
	CONFIG_DATA_TYPE_MASK_WORD_LIST = 0,
	CONFIG_DATA_TYPE_STRING_TABLE = 1,
	CONFIG_DATA_TYPE_ITEM_DROP_BAG = 2,
	CONFIG_DATA_TYPE_SCRIPT_LIST = 3,
	CONFIG_DATA_TYPE_ITEM_CONFIG = 4,
	CONFIG_DATA_TYPE_GAME_SCATTERED_CONFIG = 5,
	CONFIG_DATA_TYPE_SHOP_CONFIG = 6,
	CONFIG_DATA_TYPE_QUEST_CONFIG = 7,
	CONFIG_DATA_TYPE_RANK_CONFIG = 8,
	CONFIG_DATA_TYPE_CHAR_CONFIG = 9,
	CONFIG_DATA_TYPE_SCENE_CONFIG = 10,
	CONFIG_DATA_TYPE_SKILL_CONFIG = 11,
	CONFIG_DATA_TYPE_MAP_BLOCKS = 12,
	CONFIG_DATA_TYPE_MAX = 13,

};





