if MMO==nil then
	MMO={};
end



MMO.GM_COMMAND_TYPE=
{
	GM_COMMAND_TYPE_NONE = 0,
	GM_COMMAND_TYPE_SENDMAIL = 1,
	GM_COMMAND_TYPE_RECHARGE = 2,
	GM_COMMAND_TYPE_QUERYINFO = 3,
	GM_COMMAND_TYPE_CHANGEATTR = 4,
	GM_COMMAND_TYPE_QUERYONLINE = 5,
	GM_COMMAND_TYPE_QUERYGRADE = 6,
	GM_COMMAND_TYPE_LOGINMANAGER = 7,
	GM_COMMAND_TYPE_SILENCE = 8,
	GM_COMMAND_TYPE_DEL = 9,
	GM_COMMAND_TYPE_SENDNOTICE = 10,
	GM_COMMAND_TYPE_QUERYNOTICE = 11,
	GM_COMMAND_TYPE_DELNOTICE = 12,
	GM_COMMAND_TYPE_SHUTDOWN = 13,
	GM_COMMAND_TYPE_DIY = 14,

};




MMO.GM_PLAYER_ATTR=
{
	GM_PLAYER_ATTR_TYPE_ID = 1,
	GM_PLAYER_ATTR_TYPE_ACCOUNTID = 2,
	GM_PLAYER_ATTR_TYPE_NICKNAME = 3,
	GM_PLAYER_ATTR_TYPE_LEVEL = 4,
	GM_PLAYER_ATTR_TYPE_EXP = 5,
	GM_PLAYER_ATTR_TYPE_LEVELUPEXP = 6,
	GM_PLAYER_ATTR_TYPE_COIN = 7,
	GM_PLAYER_ATTR_TYPE_CREDIT = 8,
	GM_PLAYER_ATTR_TYPE_VIPLEVEL = 9,
	GM_PLAYER_ATTR_TYPE_ITEM = 10,
	GM_PLAYER_ATTR_TYPE_DEL_ITEM = 11,

};




MMO.GM_RESPOND_CODE=
{
	GM_RESPOND_CODE_SUCCESS = 0,
	GM_RESPOND_CODE_PARAM = 1,
	GM_RESPOND_CODE_FAILED = 2,

};




MMO.GM_TYPE=
{
	GM_TYPE_NONE = 0,
	GM_TYPE_ONLINE_GM = 1,
	GM_TYPE_RANK_GM = 1<<1,

};





