if MMO==nil then
	MMO={};
end



MMO.CELEBRATION_TRIGGER_TYPE=
{
	CELEBRATION_TRIGGER_TYPE_ABSOLUTE_TIME = 0,
	CELEBRATION_TRIGGER_TYPE_CREATE_TIME = 1,
	CELEBRATION_TRIGGER_TYPE_MAX = 2,

};




MMO.CELEBRATION_TYPE=
{
	CELEBRATION_TYPE_SCRIPT = 0,
	CELEBRATION_TYPE_MAX = 1,

};




MMO.PLAYER_DATA_FETCH_TYPE=
{
	PLAYER_DATA_FETCH_TYPE_SELF = 0,
	PLAYER_DATA_FETCH_TYPE_OTHER = 1,
	PLAYER_DATA_FETCH_TYPE_FIND_ROLE = 2,
	PLAYER_DATA_FETCH_TYPE_SIMPLE = 3,
	PLAYER_DATA_FETCH_TYPE_STELLAR_OWNER = 4,

};




MMO.MSG_RESULT=
{
	MSR_SUCCEED = 0,
	MSR_FAILED = 1,
	MSR_ERR_CONFIG = 2,
	MSR_ERR_PARAMS = 3,
	MSR_MISS = 4,
	MSR_NEED_QUEUE = 5,
	MSR_VERSION_ERROR = 6,
	MSR_SYSTEM_BUSY = 7,
	MSR_ACCOUNT_OR_PASSWORD_ERROR = 8,
	MSR_NEED_DYNAMIC_AUTH = 9,
	MSR_ALREADY_LOGIN = 10,
	MSR_SYSTEM_CLOSED = 11,
	MSR_ACCOUNT_IS_BLOCKED = 12,
	MSR_ACCOUNT_NAME_ALREAD_USED = 13,
	MSR_INVALID_REGISTER_CODE = 14,
	MSR_DEVICE_ID_NOT_EXIST = 15,
	MSR_ACCOUNT_NOT_EXIST = 16,
	MSR_ACCOUNT_ALREADY_BIND_DEVICE = 17,
	MSR_INVALID_LOGIN_SESSION = 18,
	MSR_NEED_ACTIVE = 19,
	MSR_INVALID_ACTIVE_CODE = 20,
	MSR_ACTIVE_CODE_ALREADY_USED = 21,
	MSR_ENTER_QUEUE_IS_FULL = 22,
	MSR_ENTER_QUEUE_IS_EMPTY = 23,
	MSR_ACCOUNT_REGISTER_CLOSED = 24,
	MSR_INVALID_SERVER_AREA = 25,
	MSR_ALREADY_EXIST = 26,
	MSR_BAG_FULL = 27,
	MSR_CALL_SEQUENCE_ERROR = 28,
	MSR_CAN_NOT_CAST_NOW = 29,
	MSR_CASTER_MUST_BE_PLAYER = 30,
	MSR_CONFIG_DATA_ERROR = 31,
	MSR_CUR_STATE_CAN_NOT_USE_SKILL = 32,
	MSR_DATA_NEED_SAVE = 33,
	MSR_HAVE_BUFF = 34,
	MSR_HAVE_MASK_WORD = 35,
	MSR_HAVE_SPECIFY_SKILL = 36,
	MSR_HOLD_BY_ANOTHER = 37,
	MSR_INVALID_BAG = 38,
	MSR_INVALID_BUFF = 39,
	MSR_INVALID_CASTER = 40,
	MSR_INVALID_CHAR_STATE = 41,
	MSR_INVALID_RES_RANGE = 42,
	MSR_INVALID_ID = 43,
	MSR_INVALID_INDEX = 44,
	MSR_INVALID_ITEM_TYPE = 45,
	MSR_INVALID_LEVEL_RANGE = 46,
	MSR_INVALID_PARAM = 47,
	MSR_INVALID_POSITION = 48,
	MSR_INVALID_PROFRESSION = 49,
	MSR_INVALID_QUEST_ACTIONID = 50,
	MSR_INVALID_RACE_TYPE = 51,
	MSR_INVALID_RANGE = 52,
	MSR_INVALID_SCENE = 53,
	MSR_INVALID_SKILL = 54,
	MSR_INVALID_SLOT = 55,
	MSR_INVALID_STATUS = 56,
	MSR_INVALID_TARGET = 57,
	MSR_INVALID_TARGET_CHAR_STATE = 58,
	MSR_INVALID_TARGET_RES_RANGE = 59,
	MSR_INVALID_TARGET_LEVEL_RANGE = 60,
	MSR_INVALID_TARGET_POS = 61,
	MSR_INVALID_TARGET_RACE_TYPE = 62,
	MSR_INVALID_TYPE = 63,
	MSR_IN_COOLDOWN = 64,
	MSR_IN_PREPARE = 65,
	MSR_IN_SILENCE = 66,
	MSR_IS_BUSY = 67,
	MSR_IS_CLOSED = 68,
	MSR_IS_EXPIRED = 69,
	MSR_IS_FULL = 70,
	MSR_IS_LIMIT_OPERATION = 71,
	MSR_ITEM_CAN_NOT_BE_USED = 72,
	MSR_ITEM_HOLD_LIMIT = 73,
	MSR_ITEM_NOT_EXIST = 74,
	MSR_LEVEL_NOT_MATCH = 75,
	MSR_LIMIT_NOT_MATCH = 76,
	MSR_LUA_ERROR = 77,
	MSR_LUA_MISS = 78,
	MSR_LUA_YIELD = 79,
	MSR_NAME_ALREAD_USED = 80,
	MSR_NEED_WAIT = 81,
	MSR_NOT_ENOUGH_CREDIT = 82,
	MSR_NOT_ENOUGH_HP = 83,
	MSR_NOT_ENOUGH_ITEM = 84,
	MSR_NOT_ENOUGH_MATERIAL = 85,
	MSR_NOT_ENOUGH_MP = 86,
	MSR_NOT_EXIST = 87,
	MSR_NOT_EQUIP_ITEM = 88,
	MSR_NOT_HAVE_BUFF = 89,
	MSR_NOT_HAVE_PET = 90,
	MSR_NOT_HAVE_RIGHT = 91,
	MSR_NOT_HAVE_SPECIFY_SKILL = 92,
	MSR_ONE_ADVANCE_EFFECT_ALREADY_EXIST = 93,
	MSR_ONE_SKILL_IN_CASTING = 94,
	MSR_OPERATION_ALREADY_EXCUTED = 95,
	MSR_OUT_OF_RANGE = 96,
	MSR_PLAYER_DATA_NOT_EXIST = 97,
	MSR_PREV_OPERATION_NOT_FINISH = 98,
	MSR_QUEST_CAN_NOT_FINISH_NOW = 99,
	MSR_QUEST_NOT_ACTIVE = 100,
	MSR_QUEST_NOT_EXIST = 101,
	MSR_QUEUE_FULL = 102,
	MSR_REACH_MAX = 103,
	MSR_REFUSE = 104,
	MSR_ROLE_NOT_EXIST = 105,
	MSR_SCENE_NOT_EXIST = 106,
	MSR_SHOP_BUY_LIMIT = 107,
	MSR_SHOP_GOODS_NOT_EXIST = 108,
	MSR_SHOP_NOT_EXIST = 109,
	MSR_SYSTEM_NOT_READY = 110,
	MSR_TARGET_RES_IS_FULL = 111,
	MSR_TARGET_NOT_EXIST = 112,
	MSR_TARGET_NOT_HAVE_BUFF = 113,
	MSR_TARGET_TOO_STRONG = 114,
	MSR_TOO_BIG = 115,
	MSR_NOT_ENOUGH_EMPTY_SKILL_SLOT = 116,
	MSR_PET_FULL = 117,
	MSR_REQUIRE_QUEST_NOT_MATCH = 118,
	MSR_MUST_NO_EQUIP_ITEM = 119,
	MSR_NOT_BAG_FREE_SIZE = 120,
	MSR_EXCLUSION_QUEST_EXIST = 121,
	MSR_NOT_IN_SCENE = 122,
	MSR_ELEMENT_NOT_MARCH = 123,
	MSR_EXCUTING = 124,
	MSR_CREATE_DUPLICATE_FAILED = 125,
	MSR_TELEPORT_RANGE_NEED = 126,
	MSR_GM_NEED = 127,
	MSR_PLAYER_IS_ENTERING = 128,
	MSR_PATH_ERR = 129,
	MSR_PATH_CORRECT = 130,
	MSR_NPC_NOT_EXIST = 131,
	MSR_NPC_CONFIG_ERR = 132,
	MSR_DIE_ERR = 133,
	MSR_EQUIP_POS_ERR = 134,
	MSR_ITEM_INDEX_ERR = 135,
	MSR_COUNT_NOT_ENOUGH = 136,
	MSR_CAN_NOT_MOVE_NOW = 137,
	MSR_TARGET_CAN_NOT_REACH = 138,
	MSR_NOT_NEED_MOVE = 139,
	MSR_MAX = 140,

};




MMO.PRICE_LIST_FLAG=
{
	PRICE_LIST_FLAG_AUTO_RESET = 1,
	PRICE_LIST_FLAG_GLOBAL = (1<<1),

};




MMO.PRICE_LIST_INC_TYPE=
{
	PRICE_LIST_INC_TYPE_NO_LIMIT = 0,
	PRICE_LIST_INC_TYPE_LIMITED = 1,
	PRICE_LIST_INC_TYPE_CYCLE = 2,
	PRICE_LIST_INC_TYPE_MAX = 3,

};




MMO.PRICE_LIST_TYPE=
{
	PRICE_LIST_TYPE_NONE = 0,
	PRICE_LIST_TYPE_EXCHANGE_RES = 1,
	PRICE_LIST_TYPE_BUILDING_TRUST = 2,
	PRICE_LIST_TYPE_MAX = 3,

};




MMO.QUEST_ACTION_TYPE=
{
	QUEST_ACTION_TYPE_TREASURE_BOX = 0,
	QUEST_ACTION_TYPE_NPC = 1,
	QUEST_ACTION_TYPE_RESOURCE = 2,
	QUEST_ACTION_TYPE_MAX = 3,

};




MMO.QUEST_COMPL_CON_TYPE=
{
	QUEST_COMPL_CON_TYPE_SCRIPT = 0,
	QUEST_COMPL_CON_TYPE_FINISH_QUEST = 1,
	QUEST_COMPL_CON_TYPE_FINISH_ACTION = 2,
	QUEST_COMPL_CON_TYPE_FINISH_ACTION_BY_TYPE = 3,
	QUEST_COMPL_CON_TYPE_LOGIN_DAYS = 4,
	QUEST_COMPL_CON_TYPE_VIP_LEVEL = 5,
	QUEST_COMPL_CON_TYPE_USE_ITEM = 6,
	QUEST_COMPL_CON_TYPE_USE_ITEM_BY_TYPE = 7,
	QUEST_COMPL_CON_TYPE_COST_ITEM = 8,
	QUEST_COMPL_CON_TYPE_GET_ITEM = 9,
	QUEST_COMPL_CON_TYPE_HAVE_ITEM = 10,
	QUEST_COMPL_CON_TYPE_SHOP_BUY_COUNT = 11,
	QUEST_COMPL_CON_TYPE_ALL_SHOP_BUY_COUNT = 12,
	QUEST_COMPL_CON_TYPE_RECHARGE_AMOUNT = 13,
	QUEST_COMPL_CON_TYPE_TOTAL_RECHARGE_AMOUNT = 14,
	QUEST_COMPL_CON_TYPE_MAX = 15,

};




MMO.QUEST_FLAG=
{
	QUEST_FLAG_REFRESH_ONCE = 1,
	QUEST_FLAG_GLOBAL = (1<<1),

};




MMO.QUEST_RESULT_TYPE=
{
	QUEST_RESULT_TYPE_ITEM_REWARD = 0,
	QUEST_RESULT_TYPE_BOX_REWARD = 1,
	QUEST_RESULT_TYPE_REFRESH_SHOP = 2,
	QUEST_RESULT_TYPE_MAX = 3,

};




MMO.QUEST_TRIGGER_TYPE=
{
	QUEST_TRIGGER_TYPE_GAME_TIME_RANGE = 0,
	QUEST_TRIGGER_TYPE_REAL_TIME_RANGE = 1,
	QUEST_TRIGGER_TYPE_REAL_DATE_RANGE = 2,
	QUEST_TRIGGER_TYPE_HAVE_CAPTAIN = 3,
	QUEST_TRIGGER_TYPE_FINISH_QUEST = 4,
	QUEST_TRIGGER_TYPE_VIP_LEVEL = 5,
	QUEST_TRIGGER_TYPE_PICK_QUEST_REWARD = 6,
	QUEST_TRIGGER_TYPE_CREATE_PAST_DAY = 7,
	QUEST_TRIGGER_TYPE_BUY_SHOP_GOODS = 8,
	QUEST_TRIGGER_TYPE_MAX = 9,

};




MMO.QUEST_TYPE=
{
	QUEST_TYPE_NONE = 0,
	QUEST_TYPE_ACHIEVEMENT = 1,
	QUEST_TYPE_QUEST = 2,
	QUEST_TYPE_QUEST_DAILY = 3,
	QUEST_TYPE_QUEST_WEEKLY = 4,
	QUEST_TYPE_CELEBRATION = 5,
	QUEST_TYPE_NOVICE = 6,
	QUEST_TYPE_MAX = 7,

};




MMO.SHOP_FLAG=
{
	SHOP_FLAG_CASH = 1,
	SHOP_FLAG_GLOBAL = (1<<1),
	SHOP_FLAG_CELEBRATION_SHOP = (1<<2),

};




MMO.SHOP_GOODS_FLAG=
{
	SHOP_GOODS_FLAG_NO_REFRESH = 1,
	SHOP_GOODS_FLAG_HIDE_ON_BUY_LIMIT = 1<<1,
	SHOP_GOODS_FLAG_HIDE_ON_SELL_OUT = 1<<2,
	SHOP_GOODS_FLAG_IS_DROP_BAG = 1<<3,
	SHOP_GOODS_FLAG_GIFT_IS_DROP_BAG = 1<<4,
	SHOP_GOODS_FLAG_PERMANENT_BUY_COUNT_LIMIT = 1<<5,
	SHOP_GOODS_FLAG_GROUP_BUY_COUNT_LIMIT = 1<<6,

};




MMO.SHOP_GOODS_LIMIT_TYPE=
{
	SHOP_GOODS_LIMIT_TYPE_VIP_LEVEL = 0,
	SHOP_GOODS_LIMIT_TYPE_DATE = 1,
	SHOP_GOODS_LIMIT_TYPE_BUY_GOODS = 2,
	SHOP_GOODS_LIMIT_TYPE_PAY_COUNT = 3,
	SHOP_GOODS_LIMIT_TYPE_CREATE_TIME = 4,
	SHOP_GOODS_LIMIT_TYPE_TOTAL_RECHARGE = 5,
	SHOP_GOODS_LIMIT_TYPE_MAX = 6,

};




MMO.SHOP_GOODS_TYPE=
{
	SHOP_GOODS_TYPE_NORMAL = 0,
	SHOP_GOODS_TYPE_CASH = 1,
	SHOP_GOODS_TYPE_MAX = 2,

};




MMO.SHOP_RESET_TYPE=
{
	SHOP_RESET_TYPE_BY_DAY = 0,
	SHOP_RESET_TYPE_BY_WEEK = 1,
	SHOP_RESET_TYPE_BY_MONTH = 2,
	SHOP_RESET_TYPE_BY_HOUR = 3,
	SHOP_RESET_TYPE_NO_RESET = 4,
	SHOP_RESET_TYPE_MAX = 5,

};




MMO.SHOP_TYPE=
{
	SHOP_TYPE_FIX_GOODS = 0,
	SHOP_TYPE_DISCOUNT_GOODS = 1,
	SHOP_TYPE_DAILY_DEAL_GOODS = 2,
	SHOP_TYPE_MAX = 3,

};




MMO.VIRTUAL_ITEM_TYPE=
{
	VIRTUAL_ITEM_TYPE_VIP_EXP = 20000004,

};





