// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: t1.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_t1_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_t1_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3010000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3010001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "p1.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_t1_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_t1_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_t1_2eproto;
namespace t1 {
class MSG_BASE;
class MSG_BASEDefaultTypeInternal;
extern MSG_BASEDefaultTypeInternal _MSG_BASE_default_instance_;
}  // namespace t1
PROTOBUF_NAMESPACE_OPEN
template<> ::t1::MSG_BASE* Arena::CreateMaybeMessage<::t1::MSG_BASE>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace t1 {

// ===================================================================

class MSG_BASE :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:t1.MSG_BASE) */ {
 public:
  MSG_BASE();
  virtual ~MSG_BASE();

  MSG_BASE(const MSG_BASE& from);
  MSG_BASE(MSG_BASE&& from) noexcept
    : MSG_BASE() {
    *this = ::std::move(from);
  }

  inline MSG_BASE& operator=(const MSG_BASE& from) {
    CopyFrom(from);
    return *this;
  }
  inline MSG_BASE& operator=(MSG_BASE&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MSG_BASE& default_instance();

  enum MsgCase {
    kMSGHEARTBEAT = 1000,
    kMSGLEADERREG = 1001,
    kMSGLEADERSERVERLIST = 1002,
    kMSGHEARTBEATRES = 2000,
    kMSGLEADERREGRES = 2001,
    kMSGLEADERSERVERLISTRES = 2002,
    kMSGLEADERBROADCASTADD = 3001,
    kMSGLEADERBROADCASTREMOVE = 3002,
    MSG_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MSG_BASE* internal_default_instance() {
    return reinterpret_cast<const MSG_BASE*>(
               &_MSG_BASE_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MSG_BASE& a, MSG_BASE& b) {
    a.Swap(&b);
  }
  inline void Swap(MSG_BASE* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MSG_BASE* New() const final {
    return CreateMaybeMessage<MSG_BASE>(nullptr);
  }

  MSG_BASE* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MSG_BASE>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MSG_BASE& from);
  void MergeFrom(const MSG_BASE& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* InternalSerializeWithCachedSizesToArray(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MSG_BASE* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "t1.MSG_BASE";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_t1_2eproto);
    return ::descriptor_table_t1_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMSGHEARTBEATFieldNumber = 1000,
    kMSGLEADERREGFieldNumber = 1001,
    kMSGLEADERSERVERLISTFieldNumber = 1002,
    kMSGHEARTBEATRESFieldNumber = 2000,
    kMSGLEADERREGRESFieldNumber = 2001,
    kMSGLEADERSERVERLISTRESFieldNumber = 2002,
    kMSGLEADERBROADCASTADDFieldNumber = 3001,
    kMSGLEADERBROADCASTREMOVEFieldNumber = 3002,
  };
  // .p1.MSG_HEARTBEAT MSG_HEARTBEAT = 1000;
  bool has_msg_heartbeat() const;
  private:
  bool _internal_has_msg_heartbeat() const;
  public:
  void clear_msg_heartbeat();
  const ::p1::MSG_HEARTBEAT& msg_heartbeat() const;
  ::p1::MSG_HEARTBEAT* release_msg_heartbeat();
  ::p1::MSG_HEARTBEAT* mutable_msg_heartbeat();
  void set_allocated_msg_heartbeat(::p1::MSG_HEARTBEAT* msg_heartbeat);
  private:
  const ::p1::MSG_HEARTBEAT& _internal_msg_heartbeat() const;
  ::p1::MSG_HEARTBEAT* _internal_mutable_msg_heartbeat();
  public:

  // .p1.MSG_LEADER_REG MSG_LEADER_REG = 1001;
  bool has_msg_leader_reg() const;
  private:
  bool _internal_has_msg_leader_reg() const;
  public:
  void clear_msg_leader_reg();
  const ::p1::MSG_LEADER_REG& msg_leader_reg() const;
  ::p1::MSG_LEADER_REG* release_msg_leader_reg();
  ::p1::MSG_LEADER_REG* mutable_msg_leader_reg();
  void set_allocated_msg_leader_reg(::p1::MSG_LEADER_REG* msg_leader_reg);
  private:
  const ::p1::MSG_LEADER_REG& _internal_msg_leader_reg() const;
  ::p1::MSG_LEADER_REG* _internal_mutable_msg_leader_reg();
  public:

  // .p1.MSG_LEADER_SERVER_LIST MSG_LEADER_SERVER_LIST = 1002;
  bool has_msg_leader_server_list() const;
  private:
  bool _internal_has_msg_leader_server_list() const;
  public:
  void clear_msg_leader_server_list();
  const ::p1::MSG_LEADER_SERVER_LIST& msg_leader_server_list() const;
  ::p1::MSG_LEADER_SERVER_LIST* release_msg_leader_server_list();
  ::p1::MSG_LEADER_SERVER_LIST* mutable_msg_leader_server_list();
  void set_allocated_msg_leader_server_list(::p1::MSG_LEADER_SERVER_LIST* msg_leader_server_list);
  private:
  const ::p1::MSG_LEADER_SERVER_LIST& _internal_msg_leader_server_list() const;
  ::p1::MSG_LEADER_SERVER_LIST* _internal_mutable_msg_leader_server_list();
  public:

  // .p1.MSG_HEARTBEAT MSG_HEARTBEAT_RES = 2000;
  bool has_msg_heartbeat_res() const;
  private:
  bool _internal_has_msg_heartbeat_res() const;
  public:
  void clear_msg_heartbeat_res();
  const ::p1::MSG_HEARTBEAT& msg_heartbeat_res() const;
  ::p1::MSG_HEARTBEAT* release_msg_heartbeat_res();
  ::p1::MSG_HEARTBEAT* mutable_msg_heartbeat_res();
  void set_allocated_msg_heartbeat_res(::p1::MSG_HEARTBEAT* msg_heartbeat_res);
  private:
  const ::p1::MSG_HEARTBEAT& _internal_msg_heartbeat_res() const;
  ::p1::MSG_HEARTBEAT* _internal_mutable_msg_heartbeat_res();
  public:

  // .p1.MSG_LEADER_REG_RES MSG_LEADER_REG_RES = 2001;
  bool has_msg_leader_reg_res() const;
  private:
  bool _internal_has_msg_leader_reg_res() const;
  public:
  void clear_msg_leader_reg_res();
  const ::p1::MSG_LEADER_REG_RES& msg_leader_reg_res() const;
  ::p1::MSG_LEADER_REG_RES* release_msg_leader_reg_res();
  ::p1::MSG_LEADER_REG_RES* mutable_msg_leader_reg_res();
  void set_allocated_msg_leader_reg_res(::p1::MSG_LEADER_REG_RES* msg_leader_reg_res);
  private:
  const ::p1::MSG_LEADER_REG_RES& _internal_msg_leader_reg_res() const;
  ::p1::MSG_LEADER_REG_RES* _internal_mutable_msg_leader_reg_res();
  public:

  // .p1.MSG_LEADER_SERVER_LIST_RES MSG_LEADER_SERVER_LIST_RES = 2002;
  bool has_msg_leader_server_list_res() const;
  private:
  bool _internal_has_msg_leader_server_list_res() const;
  public:
  void clear_msg_leader_server_list_res();
  const ::p1::MSG_LEADER_SERVER_LIST_RES& msg_leader_server_list_res() const;
  ::p1::MSG_LEADER_SERVER_LIST_RES* release_msg_leader_server_list_res();
  ::p1::MSG_LEADER_SERVER_LIST_RES* mutable_msg_leader_server_list_res();
  void set_allocated_msg_leader_server_list_res(::p1::MSG_LEADER_SERVER_LIST_RES* msg_leader_server_list_res);
  private:
  const ::p1::MSG_LEADER_SERVER_LIST_RES& _internal_msg_leader_server_list_res() const;
  ::p1::MSG_LEADER_SERVER_LIST_RES* _internal_mutable_msg_leader_server_list_res();
  public:

  // .p1.MSG_LEADER_BROADCAST_ADD MSG_LEADER_BROADCAST_ADD = 3001;
  bool has_msg_leader_broadcast_add() const;
  private:
  bool _internal_has_msg_leader_broadcast_add() const;
  public:
  void clear_msg_leader_broadcast_add();
  const ::p1::MSG_LEADER_BROADCAST_ADD& msg_leader_broadcast_add() const;
  ::p1::MSG_LEADER_BROADCAST_ADD* release_msg_leader_broadcast_add();
  ::p1::MSG_LEADER_BROADCAST_ADD* mutable_msg_leader_broadcast_add();
  void set_allocated_msg_leader_broadcast_add(::p1::MSG_LEADER_BROADCAST_ADD* msg_leader_broadcast_add);
  private:
  const ::p1::MSG_LEADER_BROADCAST_ADD& _internal_msg_leader_broadcast_add() const;
  ::p1::MSG_LEADER_BROADCAST_ADD* _internal_mutable_msg_leader_broadcast_add();
  public:

  // .p1.MSG_LEADER_BROADCAST_REMOVE MSG_LEADER_BROADCAST_REMOVE = 3002;
  bool has_msg_leader_broadcast_remove() const;
  private:
  bool _internal_has_msg_leader_broadcast_remove() const;
  public:
  void clear_msg_leader_broadcast_remove();
  const ::p1::MSG_LEADER_BROADCAST_REMOVE& msg_leader_broadcast_remove() const;
  ::p1::MSG_LEADER_BROADCAST_REMOVE* release_msg_leader_broadcast_remove();
  ::p1::MSG_LEADER_BROADCAST_REMOVE* mutable_msg_leader_broadcast_remove();
  void set_allocated_msg_leader_broadcast_remove(::p1::MSG_LEADER_BROADCAST_REMOVE* msg_leader_broadcast_remove);
  private:
  const ::p1::MSG_LEADER_BROADCAST_REMOVE& _internal_msg_leader_broadcast_remove() const;
  ::p1::MSG_LEADER_BROADCAST_REMOVE* _internal_mutable_msg_leader_broadcast_remove();
  public:

  void clear_msg();
  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:t1.MSG_BASE)
 private:
  class _Internal;
  void set_has_msg_heartbeat();
  void set_has_msg_leader_reg();
  void set_has_msg_leader_server_list();
  void set_has_msg_heartbeat_res();
  void set_has_msg_leader_reg_res();
  void set_has_msg_leader_server_list_res();
  void set_has_msg_leader_broadcast_add();
  void set_has_msg_leader_broadcast_remove();

  inline bool has_msg() const;
  inline void clear_has_msg();

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  union MsgUnion {
    MsgUnion() {}
    ::p1::MSG_HEARTBEAT* msg_heartbeat_;
    ::p1::MSG_LEADER_REG* msg_leader_reg_;
    ::p1::MSG_LEADER_SERVER_LIST* msg_leader_server_list_;
    ::p1::MSG_HEARTBEAT* msg_heartbeat_res_;
    ::p1::MSG_LEADER_REG_RES* msg_leader_reg_res_;
    ::p1::MSG_LEADER_SERVER_LIST_RES* msg_leader_server_list_res_;
    ::p1::MSG_LEADER_BROADCAST_ADD* msg_leader_broadcast_add_;
    ::p1::MSG_LEADER_BROADCAST_REMOVE* msg_leader_broadcast_remove_;
  } msg_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_t1_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MSG_BASE

// .p1.MSG_HEARTBEAT MSG_HEARTBEAT = 1000;
inline bool MSG_BASE::_internal_has_msg_heartbeat() const {
  return msg_case() == kMSGHEARTBEAT;
}
inline bool MSG_BASE::has_msg_heartbeat() const {
  return _internal_has_msg_heartbeat();
}
inline void MSG_BASE::set_has_msg_heartbeat() {
  _oneof_case_[0] = kMSGHEARTBEAT;
}
inline ::p1::MSG_HEARTBEAT* MSG_BASE::release_msg_heartbeat() {
  // @@protoc_insertion_point(field_release:t1.MSG_BASE.MSG_HEARTBEAT)
  if (has_msg_heartbeat()) {
    clear_has_msg();
      ::p1::MSG_HEARTBEAT* temp = msg_.msg_heartbeat_;
    msg_.msg_heartbeat_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::p1::MSG_HEARTBEAT& MSG_BASE::_internal_msg_heartbeat() const {
  return _internal_has_msg_heartbeat()
      ? *msg_.msg_heartbeat_
      : *reinterpret_cast< ::p1::MSG_HEARTBEAT*>(&::p1::_MSG_HEARTBEAT_default_instance_);
}
inline const ::p1::MSG_HEARTBEAT& MSG_BASE::msg_heartbeat() const {
  // @@protoc_insertion_point(field_get:t1.MSG_BASE.MSG_HEARTBEAT)
  return _internal_msg_heartbeat();
}
inline ::p1::MSG_HEARTBEAT* MSG_BASE::_internal_mutable_msg_heartbeat() {
  if (!_internal_has_msg_heartbeat()) {
    clear_msg();
    set_has_msg_heartbeat();
    msg_.msg_heartbeat_ = CreateMaybeMessage< ::p1::MSG_HEARTBEAT >(
        GetArenaNoVirtual());
  }
  return msg_.msg_heartbeat_;
}
inline ::p1::MSG_HEARTBEAT* MSG_BASE::mutable_msg_heartbeat() {
  // @@protoc_insertion_point(field_mutable:t1.MSG_BASE.MSG_HEARTBEAT)
  return _internal_mutable_msg_heartbeat();
}

// .p1.MSG_LEADER_REG MSG_LEADER_REG = 1001;
inline bool MSG_BASE::_internal_has_msg_leader_reg() const {
  return msg_case() == kMSGLEADERREG;
}
inline bool MSG_BASE::has_msg_leader_reg() const {
  return _internal_has_msg_leader_reg();
}
inline void MSG_BASE::set_has_msg_leader_reg() {
  _oneof_case_[0] = kMSGLEADERREG;
}
inline ::p1::MSG_LEADER_REG* MSG_BASE::release_msg_leader_reg() {
  // @@protoc_insertion_point(field_release:t1.MSG_BASE.MSG_LEADER_REG)
  if (has_msg_leader_reg()) {
    clear_has_msg();
      ::p1::MSG_LEADER_REG* temp = msg_.msg_leader_reg_;
    msg_.msg_leader_reg_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::p1::MSG_LEADER_REG& MSG_BASE::_internal_msg_leader_reg() const {
  return _internal_has_msg_leader_reg()
      ? *msg_.msg_leader_reg_
      : *reinterpret_cast< ::p1::MSG_LEADER_REG*>(&::p1::_MSG_LEADER_REG_default_instance_);
}
inline const ::p1::MSG_LEADER_REG& MSG_BASE::msg_leader_reg() const {
  // @@protoc_insertion_point(field_get:t1.MSG_BASE.MSG_LEADER_REG)
  return _internal_msg_leader_reg();
}
inline ::p1::MSG_LEADER_REG* MSG_BASE::_internal_mutable_msg_leader_reg() {
  if (!_internal_has_msg_leader_reg()) {
    clear_msg();
    set_has_msg_leader_reg();
    msg_.msg_leader_reg_ = CreateMaybeMessage< ::p1::MSG_LEADER_REG >(
        GetArenaNoVirtual());
  }
  return msg_.msg_leader_reg_;
}
inline ::p1::MSG_LEADER_REG* MSG_BASE::mutable_msg_leader_reg() {
  // @@protoc_insertion_point(field_mutable:t1.MSG_BASE.MSG_LEADER_REG)
  return _internal_mutable_msg_leader_reg();
}

// .p1.MSG_LEADER_SERVER_LIST MSG_LEADER_SERVER_LIST = 1002;
inline bool MSG_BASE::_internal_has_msg_leader_server_list() const {
  return msg_case() == kMSGLEADERSERVERLIST;
}
inline bool MSG_BASE::has_msg_leader_server_list() const {
  return _internal_has_msg_leader_server_list();
}
inline void MSG_BASE::set_has_msg_leader_server_list() {
  _oneof_case_[0] = kMSGLEADERSERVERLIST;
}
inline ::p1::MSG_LEADER_SERVER_LIST* MSG_BASE::release_msg_leader_server_list() {
  // @@protoc_insertion_point(field_release:t1.MSG_BASE.MSG_LEADER_SERVER_LIST)
  if (has_msg_leader_server_list()) {
    clear_has_msg();
      ::p1::MSG_LEADER_SERVER_LIST* temp = msg_.msg_leader_server_list_;
    msg_.msg_leader_server_list_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::p1::MSG_LEADER_SERVER_LIST& MSG_BASE::_internal_msg_leader_server_list() const {
  return _internal_has_msg_leader_server_list()
      ? *msg_.msg_leader_server_list_
      : *reinterpret_cast< ::p1::MSG_LEADER_SERVER_LIST*>(&::p1::_MSG_LEADER_SERVER_LIST_default_instance_);
}
inline const ::p1::MSG_LEADER_SERVER_LIST& MSG_BASE::msg_leader_server_list() const {
  // @@protoc_insertion_point(field_get:t1.MSG_BASE.MSG_LEADER_SERVER_LIST)
  return _internal_msg_leader_server_list();
}
inline ::p1::MSG_LEADER_SERVER_LIST* MSG_BASE::_internal_mutable_msg_leader_server_list() {
  if (!_internal_has_msg_leader_server_list()) {
    clear_msg();
    set_has_msg_leader_server_list();
    msg_.msg_leader_server_list_ = CreateMaybeMessage< ::p1::MSG_LEADER_SERVER_LIST >(
        GetArenaNoVirtual());
  }
  return msg_.msg_leader_server_list_;
}
inline ::p1::MSG_LEADER_SERVER_LIST* MSG_BASE::mutable_msg_leader_server_list() {
  // @@protoc_insertion_point(field_mutable:t1.MSG_BASE.MSG_LEADER_SERVER_LIST)
  return _internal_mutable_msg_leader_server_list();
}

// .p1.MSG_HEARTBEAT MSG_HEARTBEAT_RES = 2000;
inline bool MSG_BASE::_internal_has_msg_heartbeat_res() const {
  return msg_case() == kMSGHEARTBEATRES;
}
inline bool MSG_BASE::has_msg_heartbeat_res() const {
  return _internal_has_msg_heartbeat_res();
}
inline void MSG_BASE::set_has_msg_heartbeat_res() {
  _oneof_case_[0] = kMSGHEARTBEATRES;
}
inline ::p1::MSG_HEARTBEAT* MSG_BASE::release_msg_heartbeat_res() {
  // @@protoc_insertion_point(field_release:t1.MSG_BASE.MSG_HEARTBEAT_RES)
  if (has_msg_heartbeat_res()) {
    clear_has_msg();
      ::p1::MSG_HEARTBEAT* temp = msg_.msg_heartbeat_res_;
    msg_.msg_heartbeat_res_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::p1::MSG_HEARTBEAT& MSG_BASE::_internal_msg_heartbeat_res() const {
  return _internal_has_msg_heartbeat_res()
      ? *msg_.msg_heartbeat_res_
      : *reinterpret_cast< ::p1::MSG_HEARTBEAT*>(&::p1::_MSG_HEARTBEAT_default_instance_);
}
inline const ::p1::MSG_HEARTBEAT& MSG_BASE::msg_heartbeat_res() const {
  // @@protoc_insertion_point(field_get:t1.MSG_BASE.MSG_HEARTBEAT_RES)
  return _internal_msg_heartbeat_res();
}
inline ::p1::MSG_HEARTBEAT* MSG_BASE::_internal_mutable_msg_heartbeat_res() {
  if (!_internal_has_msg_heartbeat_res()) {
    clear_msg();
    set_has_msg_heartbeat_res();
    msg_.msg_heartbeat_res_ = CreateMaybeMessage< ::p1::MSG_HEARTBEAT >(
        GetArenaNoVirtual());
  }
  return msg_.msg_heartbeat_res_;
}
inline ::p1::MSG_HEARTBEAT* MSG_BASE::mutable_msg_heartbeat_res() {
  // @@protoc_insertion_point(field_mutable:t1.MSG_BASE.MSG_HEARTBEAT_RES)
  return _internal_mutable_msg_heartbeat_res();
}

// .p1.MSG_LEADER_REG_RES MSG_LEADER_REG_RES = 2001;
inline bool MSG_BASE::_internal_has_msg_leader_reg_res() const {
  return msg_case() == kMSGLEADERREGRES;
}
inline bool MSG_BASE::has_msg_leader_reg_res() const {
  return _internal_has_msg_leader_reg_res();
}
inline void MSG_BASE::set_has_msg_leader_reg_res() {
  _oneof_case_[0] = kMSGLEADERREGRES;
}
inline ::p1::MSG_LEADER_REG_RES* MSG_BASE::release_msg_leader_reg_res() {
  // @@protoc_insertion_point(field_release:t1.MSG_BASE.MSG_LEADER_REG_RES)
  if (has_msg_leader_reg_res()) {
    clear_has_msg();
      ::p1::MSG_LEADER_REG_RES* temp = msg_.msg_leader_reg_res_;
    msg_.msg_leader_reg_res_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::p1::MSG_LEADER_REG_RES& MSG_BASE::_internal_msg_leader_reg_res() const {
  return _internal_has_msg_leader_reg_res()
      ? *msg_.msg_leader_reg_res_
      : *reinterpret_cast< ::p1::MSG_LEADER_REG_RES*>(&::p1::_MSG_LEADER_REG_RES_default_instance_);
}
inline const ::p1::MSG_LEADER_REG_RES& MSG_BASE::msg_leader_reg_res() const {
  // @@protoc_insertion_point(field_get:t1.MSG_BASE.MSG_LEADER_REG_RES)
  return _internal_msg_leader_reg_res();
}
inline ::p1::MSG_LEADER_REG_RES* MSG_BASE::_internal_mutable_msg_leader_reg_res() {
  if (!_internal_has_msg_leader_reg_res()) {
    clear_msg();
    set_has_msg_leader_reg_res();
    msg_.msg_leader_reg_res_ = CreateMaybeMessage< ::p1::MSG_LEADER_REG_RES >(
        GetArenaNoVirtual());
  }
  return msg_.msg_leader_reg_res_;
}
inline ::p1::MSG_LEADER_REG_RES* MSG_BASE::mutable_msg_leader_reg_res() {
  // @@protoc_insertion_point(field_mutable:t1.MSG_BASE.MSG_LEADER_REG_RES)
  return _internal_mutable_msg_leader_reg_res();
}

// .p1.MSG_LEADER_SERVER_LIST_RES MSG_LEADER_SERVER_LIST_RES = 2002;
inline bool MSG_BASE::_internal_has_msg_leader_server_list_res() const {
  return msg_case() == kMSGLEADERSERVERLISTRES;
}
inline bool MSG_BASE::has_msg_leader_server_list_res() const {
  return _internal_has_msg_leader_server_list_res();
}
inline void MSG_BASE::set_has_msg_leader_server_list_res() {
  _oneof_case_[0] = kMSGLEADERSERVERLISTRES;
}
inline ::p1::MSG_LEADER_SERVER_LIST_RES* MSG_BASE::release_msg_leader_server_list_res() {
  // @@protoc_insertion_point(field_release:t1.MSG_BASE.MSG_LEADER_SERVER_LIST_RES)
  if (has_msg_leader_server_list_res()) {
    clear_has_msg();
      ::p1::MSG_LEADER_SERVER_LIST_RES* temp = msg_.msg_leader_server_list_res_;
    msg_.msg_leader_server_list_res_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::p1::MSG_LEADER_SERVER_LIST_RES& MSG_BASE::_internal_msg_leader_server_list_res() const {
  return _internal_has_msg_leader_server_list_res()
      ? *msg_.msg_leader_server_list_res_
      : *reinterpret_cast< ::p1::MSG_LEADER_SERVER_LIST_RES*>(&::p1::_MSG_LEADER_SERVER_LIST_RES_default_instance_);
}
inline const ::p1::MSG_LEADER_SERVER_LIST_RES& MSG_BASE::msg_leader_server_list_res() const {
  // @@protoc_insertion_point(field_get:t1.MSG_BASE.MSG_LEADER_SERVER_LIST_RES)
  return _internal_msg_leader_server_list_res();
}
inline ::p1::MSG_LEADER_SERVER_LIST_RES* MSG_BASE::_internal_mutable_msg_leader_server_list_res() {
  if (!_internal_has_msg_leader_server_list_res()) {
    clear_msg();
    set_has_msg_leader_server_list_res();
    msg_.msg_leader_server_list_res_ = CreateMaybeMessage< ::p1::MSG_LEADER_SERVER_LIST_RES >(
        GetArenaNoVirtual());
  }
  return msg_.msg_leader_server_list_res_;
}
inline ::p1::MSG_LEADER_SERVER_LIST_RES* MSG_BASE::mutable_msg_leader_server_list_res() {
  // @@protoc_insertion_point(field_mutable:t1.MSG_BASE.MSG_LEADER_SERVER_LIST_RES)
  return _internal_mutable_msg_leader_server_list_res();
}

// .p1.MSG_LEADER_BROADCAST_ADD MSG_LEADER_BROADCAST_ADD = 3001;
inline bool MSG_BASE::_internal_has_msg_leader_broadcast_add() const {
  return msg_case() == kMSGLEADERBROADCASTADD;
}
inline bool MSG_BASE::has_msg_leader_broadcast_add() const {
  return _internal_has_msg_leader_broadcast_add();
}
inline void MSG_BASE::set_has_msg_leader_broadcast_add() {
  _oneof_case_[0] = kMSGLEADERBROADCASTADD;
}
inline ::p1::MSG_LEADER_BROADCAST_ADD* MSG_BASE::release_msg_leader_broadcast_add() {
  // @@protoc_insertion_point(field_release:t1.MSG_BASE.MSG_LEADER_BROADCAST_ADD)
  if (has_msg_leader_broadcast_add()) {
    clear_has_msg();
      ::p1::MSG_LEADER_BROADCAST_ADD* temp = msg_.msg_leader_broadcast_add_;
    msg_.msg_leader_broadcast_add_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::p1::MSG_LEADER_BROADCAST_ADD& MSG_BASE::_internal_msg_leader_broadcast_add() const {
  return _internal_has_msg_leader_broadcast_add()
      ? *msg_.msg_leader_broadcast_add_
      : *reinterpret_cast< ::p1::MSG_LEADER_BROADCAST_ADD*>(&::p1::_MSG_LEADER_BROADCAST_ADD_default_instance_);
}
inline const ::p1::MSG_LEADER_BROADCAST_ADD& MSG_BASE::msg_leader_broadcast_add() const {
  // @@protoc_insertion_point(field_get:t1.MSG_BASE.MSG_LEADER_BROADCAST_ADD)
  return _internal_msg_leader_broadcast_add();
}
inline ::p1::MSG_LEADER_BROADCAST_ADD* MSG_BASE::_internal_mutable_msg_leader_broadcast_add() {
  if (!_internal_has_msg_leader_broadcast_add()) {
    clear_msg();
    set_has_msg_leader_broadcast_add();
    msg_.msg_leader_broadcast_add_ = CreateMaybeMessage< ::p1::MSG_LEADER_BROADCAST_ADD >(
        GetArenaNoVirtual());
  }
  return msg_.msg_leader_broadcast_add_;
}
inline ::p1::MSG_LEADER_BROADCAST_ADD* MSG_BASE::mutable_msg_leader_broadcast_add() {
  // @@protoc_insertion_point(field_mutable:t1.MSG_BASE.MSG_LEADER_BROADCAST_ADD)
  return _internal_mutable_msg_leader_broadcast_add();
}

// .p1.MSG_LEADER_BROADCAST_REMOVE MSG_LEADER_BROADCAST_REMOVE = 3002;
inline bool MSG_BASE::_internal_has_msg_leader_broadcast_remove() const {
  return msg_case() == kMSGLEADERBROADCASTREMOVE;
}
inline bool MSG_BASE::has_msg_leader_broadcast_remove() const {
  return _internal_has_msg_leader_broadcast_remove();
}
inline void MSG_BASE::set_has_msg_leader_broadcast_remove() {
  _oneof_case_[0] = kMSGLEADERBROADCASTREMOVE;
}
inline ::p1::MSG_LEADER_BROADCAST_REMOVE* MSG_BASE::release_msg_leader_broadcast_remove() {
  // @@protoc_insertion_point(field_release:t1.MSG_BASE.MSG_LEADER_BROADCAST_REMOVE)
  if (has_msg_leader_broadcast_remove()) {
    clear_has_msg();
      ::p1::MSG_LEADER_BROADCAST_REMOVE* temp = msg_.msg_leader_broadcast_remove_;
    msg_.msg_leader_broadcast_remove_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::p1::MSG_LEADER_BROADCAST_REMOVE& MSG_BASE::_internal_msg_leader_broadcast_remove() const {
  return _internal_has_msg_leader_broadcast_remove()
      ? *msg_.msg_leader_broadcast_remove_
      : *reinterpret_cast< ::p1::MSG_LEADER_BROADCAST_REMOVE*>(&::p1::_MSG_LEADER_BROADCAST_REMOVE_default_instance_);
}
inline const ::p1::MSG_LEADER_BROADCAST_REMOVE& MSG_BASE::msg_leader_broadcast_remove() const {
  // @@protoc_insertion_point(field_get:t1.MSG_BASE.MSG_LEADER_BROADCAST_REMOVE)
  return _internal_msg_leader_broadcast_remove();
}
inline ::p1::MSG_LEADER_BROADCAST_REMOVE* MSG_BASE::_internal_mutable_msg_leader_broadcast_remove() {
  if (!_internal_has_msg_leader_broadcast_remove()) {
    clear_msg();
    set_has_msg_leader_broadcast_remove();
    msg_.msg_leader_broadcast_remove_ = CreateMaybeMessage< ::p1::MSG_LEADER_BROADCAST_REMOVE >(
        GetArenaNoVirtual());
  }
  return msg_.msg_leader_broadcast_remove_;
}
inline ::p1::MSG_LEADER_BROADCAST_REMOVE* MSG_BASE::mutable_msg_leader_broadcast_remove() {
  // @@protoc_insertion_point(field_mutable:t1.MSG_BASE.MSG_LEADER_BROADCAST_REMOVE)
  return _internal_mutable_msg_leader_broadcast_remove();
}

inline bool MSG_BASE::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void MSG_BASE::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
inline MSG_BASE::MsgCase MSG_BASE::msg_case() const {
  return MSG_BASE::MsgCase(_oneof_case_[0]);
}
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace t1

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_t1_2eproto
