// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: p2.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "p2.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace p2 {

namespace {

const ::google::protobuf::Descriptor* MSG_P2_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MSG_P2_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_p2_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_p2_2eproto() {
  protobuf_AddDesc_p2_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "p2.proto");
  GOOGLE_CHECK(file != NULL);
  MSG_P2_descriptor_ = file->message_type(0);
  static const int MSG_P2_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_P2, name_),
  };
  MSG_P2_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      MSG_P2_descriptor_,
      MSG_P2::internal_default_instance(),
      MSG_P2_offsets_,
      -1,
      -1,
      -1,
      sizeof(MSG_P2),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MSG_P2, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_p2_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      MSG_P2_descriptor_, MSG_P2::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_p2_2eproto() {
  MSG_P2_default_instance_.Shutdown();
  delete MSG_P2_reflection_;
}

void protobuf_InitDefaults_p2_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  MSG_P2_default_instance_.DefaultConstruct();
  MSG_P2_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_p2_2eproto_once_);
void protobuf_InitDefaults_p2_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_p2_2eproto_once_,
                 &protobuf_InitDefaults_p2_2eproto_impl);
}
void protobuf_AddDesc_p2_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_p2_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\010p2.proto\022\002p2\"\026\n\006MSG_P2\022\014\n\004name\030\001 \001(\tb\006"
    "proto3", 46);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "p2.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_p2_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_p2_2eproto_once_);
void protobuf_AddDesc_p2_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_p2_2eproto_once_,
                 &protobuf_AddDesc_p2_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_p2_2eproto {
  StaticDescriptorInitializer_p2_2eproto() {
    protobuf_AddDesc_p2_2eproto();
  }
} static_descriptor_initializer_p2_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MSG_P2::kNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MSG_P2::MSG_P2()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_p2_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:p2.MSG_P2)
}

void MSG_P2::InitAsDefaultInstance() {
}

MSG_P2::MSG_P2(const MSG_P2& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:p2.MSG_P2)
}

void MSG_P2::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

MSG_P2::~MSG_P2() {
  // @@protoc_insertion_point(destructor:p2.MSG_P2)
  SharedDtor();
}

void MSG_P2::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void MSG_P2::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_P2::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MSG_P2_descriptor_;
}

const MSG_P2& MSG_P2::default_instance() {
  protobuf_InitDefaults_p2_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<MSG_P2> MSG_P2_default_instance_;

MSG_P2* MSG_P2::New(::google::protobuf::Arena* arena) const {
  MSG_P2* n = new MSG_P2;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MSG_P2::Clear() {
// @@protoc_insertion_point(message_clear_start:p2.MSG_P2)
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool MSG_P2::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:p2.MSG_P2)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string name = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "p2.MSG_P2.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:p2.MSG_P2)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:p2.MSG_P2)
  return false;
#undef DO_
}

void MSG_P2::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:p2.MSG_P2)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "p2.MSG_P2.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // @@protoc_insertion_point(serialize_end:p2.MSG_P2)
}

::google::protobuf::uint8* MSG_P2::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:p2.MSG_P2)
  // optional string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "p2.MSG_P2.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:p2.MSG_P2)
  return target;
}

size_t MSG_P2::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:p2.MSG_P2)
  size_t total_size = 0;

  // optional string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_P2::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:p2.MSG_P2)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const MSG_P2* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MSG_P2>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:p2.MSG_P2)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:p2.MSG_P2)
    UnsafeMergeFrom(*source);
  }
}

void MSG_P2::MergeFrom(const MSG_P2& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:p2.MSG_P2)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void MSG_P2::UnsafeMergeFrom(const MSG_P2& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
}

void MSG_P2::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:p2.MSG_P2)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_P2::CopyFrom(const MSG_P2& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:p2.MSG_P2)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool MSG_P2::IsInitialized() const {

  return true;
}

void MSG_P2::Swap(MSG_P2* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MSG_P2::InternalSwap(MSG_P2* other) {
  name_.Swap(&other->name_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MSG_P2::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MSG_P2_descriptor_;
  metadata.reflection = MSG_P2_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// MSG_P2

// optional string name = 1;
void MSG_P2::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& MSG_P2::name() const {
  // @@protoc_insertion_point(field_get:p2.MSG_P2.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void MSG_P2::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:p2.MSG_P2.name)
}
void MSG_P2::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:p2.MSG_P2.name)
}
void MSG_P2::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:p2.MSG_P2.name)
}
::std::string* MSG_P2::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:p2.MSG_P2.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* MSG_P2::release_name() {
  // @@protoc_insertion_point(field_release:p2.MSG_P2.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void MSG_P2::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:p2.MSG_P2.name)
}

inline const MSG_P2* MSG_P2::internal_default_instance() {
  return &MSG_P2_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace p2

// @@protoc_insertion_point(global_scope)
