// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: t1.proto

#ifndef PROTOBUF_t1_2eproto__INCLUDED
#define PROTOBUF_t1_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "p1.pb.h"
#include "p2.pb.h"
// @@protoc_insertion_point(includes)

namespace t1 {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_t1_2eproto();
void protobuf_InitDefaults_t1_2eproto();
void protobuf_AssignDesc_t1_2eproto();
void protobuf_ShutdownFile_t1_2eproto();

class MSG_TEST;

// ===================================================================

class MSG_TEST : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:t1.MSG_TEST) */ {
 public:
  MSG_TEST();
  virtual ~MSG_TEST();

  MSG_TEST(const MSG_TEST& from);

  inline MSG_TEST& operator=(const MSG_TEST& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_TEST& default_instance();

  static const MSG_TEST* internal_default_instance();

  void Swap(MSG_TEST* other);

  // implements Message ----------------------------------------------

  inline MSG_TEST* New() const { return New(NULL); }

  MSG_TEST* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MSG_TEST& from);
  void MergeFrom(const MSG_TEST& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(MSG_TEST* other);
  void UnsafeMergeFrom(const MSG_TEST& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // optional .p1.MSG_P1 p1 = 2;
  bool has_p1() const;
  void clear_p1();
  static const int kP1FieldNumber = 2;
  const ::p1::MSG_P1& p1() const;
  ::p1::MSG_P1* mutable_p1();
  ::p1::MSG_P1* release_p1();
  void set_allocated_p1(::p1::MSG_P1* p1);

  // optional .p2.MSG_P2 p2 = 3;
  bool has_p2() const;
  void clear_p2();
  static const int kP2FieldNumber = 3;
  const ::p2::MSG_P2& p2() const;
  ::p2::MSG_P2* mutable_p2();
  ::p2::MSG_P2* release_p2();
  void set_allocated_p2(::p2::MSG_P2* p2);

  // @@protoc_insertion_point(class_scope:t1.MSG_TEST)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::p1::MSG_P1* p1_;
  ::p2::MSG_P2* p2_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_t1_2eproto_impl();
  friend void  protobuf_AddDesc_t1_2eproto_impl();
  friend void protobuf_AssignDesc_t1_2eproto();
  friend void protobuf_ShutdownFile_t1_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<MSG_TEST> MSG_TEST_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MSG_TEST

// optional string name = 1;
inline void MSG_TEST::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MSG_TEST::name() const {
  // @@protoc_insertion_point(field_get:t1.MSG_TEST.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MSG_TEST::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:t1.MSG_TEST.name)
}
inline void MSG_TEST::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:t1.MSG_TEST.name)
}
inline void MSG_TEST::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:t1.MSG_TEST.name)
}
inline ::std::string* MSG_TEST::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:t1.MSG_TEST.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MSG_TEST::release_name() {
  // @@protoc_insertion_point(field_release:t1.MSG_TEST.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MSG_TEST::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:t1.MSG_TEST.name)
}

// optional .p1.MSG_P1 p1 = 2;
inline bool MSG_TEST::has_p1() const {
  return this != internal_default_instance() && p1_ != NULL;
}
inline void MSG_TEST::clear_p1() {
  if (GetArenaNoVirtual() == NULL && p1_ != NULL) delete p1_;
  p1_ = NULL;
}
inline const ::p1::MSG_P1& MSG_TEST::p1() const {
  // @@protoc_insertion_point(field_get:t1.MSG_TEST.p1)
  return p1_ != NULL ? *p1_
                         : *::p1::MSG_P1::internal_default_instance();
}
inline ::p1::MSG_P1* MSG_TEST::mutable_p1() {
  
  if (p1_ == NULL) {
    p1_ = new ::p1::MSG_P1;
  }
  // @@protoc_insertion_point(field_mutable:t1.MSG_TEST.p1)
  return p1_;
}
inline ::p1::MSG_P1* MSG_TEST::release_p1() {
  // @@protoc_insertion_point(field_release:t1.MSG_TEST.p1)
  
  ::p1::MSG_P1* temp = p1_;
  p1_ = NULL;
  return temp;
}
inline void MSG_TEST::set_allocated_p1(::p1::MSG_P1* p1) {
  delete p1_;
  p1_ = p1;
  if (p1) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:t1.MSG_TEST.p1)
}

// optional .p2.MSG_P2 p2 = 3;
inline bool MSG_TEST::has_p2() const {
  return this != internal_default_instance() && p2_ != NULL;
}
inline void MSG_TEST::clear_p2() {
  if (GetArenaNoVirtual() == NULL && p2_ != NULL) delete p2_;
  p2_ = NULL;
}
inline const ::p2::MSG_P2& MSG_TEST::p2() const {
  // @@protoc_insertion_point(field_get:t1.MSG_TEST.p2)
  return p2_ != NULL ? *p2_
                         : *::p2::MSG_P2::internal_default_instance();
}
inline ::p2::MSG_P2* MSG_TEST::mutable_p2() {
  
  if (p2_ == NULL) {
    p2_ = new ::p2::MSG_P2;
  }
  // @@protoc_insertion_point(field_mutable:t1.MSG_TEST.p2)
  return p2_;
}
inline ::p2::MSG_P2* MSG_TEST::release_p2() {
  // @@protoc_insertion_point(field_release:t1.MSG_TEST.p2)
  
  ::p2::MSG_P2* temp = p2_;
  p2_ = NULL;
  return temp;
}
inline void MSG_TEST::set_allocated_p2(::p2::MSG_P2* p2) {
  delete p2_;
  p2_ = p2;
  if (p2) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:t1.MSG_TEST.p2)
}

inline const MSG_TEST* MSG_TEST::internal_default_instance() {
  return &MSG_TEST_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace t1

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_t1_2eproto__INCLUDED
