#pragma once
 

using namespace t1;

//all -> monitor
DEF_PACKET_REGISTER_RECV(MSG_TEST);
//DEF_PACKET_REGISTER_RECV(MSG_BASE);

//monitor -> all
DEF_PACKET_REGISTER_SEND(MSG_TEST_RES);
//DEF_PACKET_REGISTER_SEND(MSG_BASE);



